Repository codehaus-plexus/plexus-utils, pull requests merged in 2021-04, with the labels that each got.

#137 Fix MXParser improve error reporting (#136)
  src/main/java/org/codehaus/plexus/util/xml/pull/MXParser.java
  src/test/java/org/codehaus/plexus/util/xml/pull/eduni_misc_Test_BjoernHoehrmannviaHST2013_09_18_Test.java
  src/test/resources/xmlconf/eduni/misc/001.xml
  src/test/resources/xmlconf/eduni/misc/002.xml
  src/test/resources/xmlconf/eduni/misc/003.xml
  src/test/resources/xmlconf/eduni/misc/004.xml
  src/test/resources/xmlconf/eduni/misc/005.xml
  src/test/resources/xmlconf/eduni/misc/006.xml
  src/test/resources/xmlconf/eduni/misc/007.xml
  src/test/resources/xmlconf/eduni/misc/008.xml
  src/test/resources/xmlconf/eduni/misc/009.xml
  src/test/resources/xmlconf/eduni/misc/ht-bh.xml
  src/test/resources/xmlconf/eduni/misc/xmlconf.xml
Labels: bug

#139 Fix MXParser fails to parse xml declaration properly (#138)
  src/main/java/org/codehaus/plexus/util/xml/pull/MXParser.java
  src/test/java/org/codehaus/plexus/util/xml/pull/IBMXML10Tests_Test_IBMXMLConformanceTestSuite_not_wftests_Test_IBMXMLConformanceTestSuite_Production32_Test.java
  src/test/java/org/codehaus/plexus/util/xml/pull/MXParserTest.java
Labels: bug

#123 Fix #116 : Java 16 support for ReflectionUtils
  src/main/java/org/codehaus/plexus/util/ReflectionUtils.java
Labels: chore, maintenance

#147 Using JDK 16 GA instead of JDK 16 EA
  .github/workflows/maven.yml
Labels: github_actions
